name = "RayTracingEngine"
uuid = "f401591d-7b24-4fa8-90ca-ed90dffaa34d"
version = "0.1.0"
authors = ["F. Capolupo"]

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Quats = "faa667c8-0f2e-4834-a931-554d4b02f32e"

[sources]
Quats = {rev = "master", url = "C:\\Users\\francesco capolupo\\OneDrive - ESA\\Desktop\\Work\\Tools\\ToolsJulia\\Packages\\Quats"}

[compat]
GeometryBasics = "0.5.10"
LinearAlgebra = "1.11.0"
Quats = "0.1.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
